# Generated by Django 5.2.8 on 2025-11-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='peso',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='salario',
            field=models.FloatField(null=True),
        ),
    ]
